#!/usr/bin/env python3
"""
Update Cell 13 to use Service Principal authentication
with fallback cache deletion if auth fails
"""

import json

print('[*] Reading notebook...')
with open('master-ai-gateway.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

print(f'[*] Total cells: {len(nb["cells"])}')

# Update Cell 13 with Service Principal auth
print('[*] Updating Cell 13 with Service Principal authentication...')

new_helper_functions = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import json\n",
        "import time\n",
        "import os\n",
        "import shutil\n",
        "from pathlib import Path\n",
        "from dotenv import load_dotenv\n",
        "from azure.mgmt.resource import ResourceManagementClient\n",
        "from azure.identity import ClientSecretCredential, AzureCliCredential\n",
        "\n",
        "print('[*] Initializing Azure authentication...')\n",
        "print()\n",
        "\n",
        "# Try to load Service Principal credentials from .azure-credentials.env\n",
        "credentials_file = '.azure-credentials.env'\n",
        "credential = None\n",
        "\n",
        "if os.path.exists(credentials_file):\n",
        "    print(f'[*] Found {credentials_file}, using Service Principal authentication')\n",
        "    load_dotenv(credentials_file)\n",
        "    \n",
        "    tenant_id = os.getenv('AZURE_TENANT_ID')\n",
        "    client_id = os.getenv('AZURE_CLIENT_ID')\n",
        "    client_secret = os.getenv('AZURE_CLIENT_SECRET')\n",
        "    \n",
        "    if tenant_id and client_id and client_secret:\n",
        "        try:\n",
        "            credential = ClientSecretCredential(\n",
        "                tenant_id=tenant_id,\n",
        "                client_id=client_id,\n",
        "                client_secret=client_secret\n",
        "            )\n",
        "            print('[OK] Service Principal credentials loaded')\n",
        "        except Exception as e:\n",
        "            print(f'[ERROR] Failed to create Service Principal credential: {e}')\n",
        "            credential = None\n",
        "    else:\n",
        "        print('[ERROR] Missing credentials in .azure-credentials.env')\n",
        "        print('[INFO] Required: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET')\n",
        "else:\n",
        "    print(f'[*] {credentials_file} not found')\n",
        "    print('[INFO] Run: create_service_principal.ps1 to create Service Principal')\n",
        "\n",
        "# Fallback to Azure CLI credential if Service Principal not available\n",
        "if credential is None:\n",
        "    print('[*] Falling back to Azure CLI authentication...')\n",
        "    try:\n",
        "        credential = AzureCliCredential()\n",
        "        print('[OK] Using Azure CLI credentials')\n",
        "    except Exception as e:\n",
        "        print(f'[ERROR] Azure CLI authentication failed: {e}')\n",
        "        print()\n",
        "        print('[ERROR] Authentication failed. Options:')\n",
        "        print('  1. Create Service Principal: run create_service_principal.ps1')\n",
        "        print('  2. Clear Azure CLI cache and re-login:')\n",
        "        print('     - Delete: %USERPROFILE%\\\\.azure')\n",
        "        print('     - Run: az login')\n",
        "        raise Exception('Authentication failed')\n",
        "\n",
        "print()\n",
        "\n",
        "# Verify subscription ID from config\n",
        "if not subscription_id or len(subscription_id) < 10:\n",
        "    raise Exception('Please set your subscription_id in Cell 11')\n",
        "\n",
        "print(f'[OK] Using Subscription ID: {subscription_id}')\n",
        "\n",
        "# Create Resource Management Client\n",
        "print('[*] Creating Azure Resource Management client...')\n",
        "try:\n",
        "    resource_client = ResourceManagementClient(credential, subscription_id)\n",
        "    # Test connection by listing resource groups\n",
        "    list(resource_client.resource_groups.list())\n",
        "    print('[OK] Azure SDK initialized and connection verified')\n",
        "except Exception as e:\n",
        "    print(f'[ERROR] Failed to initialize Resource Management client: {e}')\n",
        "    print()\n",
        "    print('[INFO] If you see MSAL or cache errors, try clearing Azure CLI cache:')\n",
        "    print('       rd /s /q \"%USERPROFILE%\\\\.azure\"')\n",
        "    print('       az login')\n",
        "    raise e\n",
        "\n",
        "print()\n",
        "\n",
        "def compile_bicep(bicep_file):\n",
        "    \"\"\"Compile Bicep to JSON\"\"\"\n",
        "    print(f'[*] Compiling {bicep_file}...')\n",
        "    \n",
        "    json_file = bicep_file.replace('.bicep', '.json')\n",
        "    \n",
        "    # Check if JSON already exists and is newer than bicep\n",
        "    if os.path.exists(json_file):\n",
        "        bicep_time = os.path.getmtime(bicep_file)\n",
        "        json_time = os.path.getmtime(json_file)\n",
        "        if json_time > bicep_time:\n",
        "            print(f'[OK] Using existing {json_file} (newer than .bicep)')\n",
        "            return json_file\n",
        "    \n",
        "    # Compile using az bicep\n",
        "    result = os.system(f'az bicep build --file {bicep_file}')\n",
        "    \n",
        "    if result != 0:\n",
        "        print(f'[ERROR] Compilation failed')\n",
        "        print(f'[INFO] You can manually compile: az bicep build --file {bicep_file}')\n",
        "        return False\n",
        "    \n",
        "    print(f'[OK] Compiled to {json_file}')\n",
        "    return json_file\n",
        "\n",
        "def check_resource_group_exists(rg_name):\n",
        "    \"\"\"Check if resource group exists\"\"\"\n",
        "    try:\n",
        "        resource_client.resource_groups.get(rg_name)\n",
        "        return True\n",
        "    except:\n",
        "        return False\n",
        "\n",
        "def check_deployment_exists(rg_name, deployment_name):\n",
        "    \"\"\"Check if deployment exists and succeeded\"\"\"\n",
        "    try:\n",
        "        deployment = resource_client.deployments.get(rg_name, deployment_name)\n",
        "        if deployment.properties.provisioning_state == 'Succeeded':\n",
        "            return True, deployment\n",
        "        else:\n",
        "            return False, deployment\n",
        "    except:\n",
        "        return False, None\n",
        "\n",
        "def deploy_template(rg_name, deployment_name, template_file, parameters_dict):\n",
        "    \"\"\"Deploy ARM template using Azure SDK\"\"\"\n",
        "    print(f'[*] Deploying {deployment_name}...')\n",
        "    \n",
        "    # Read template\n",
        "    with open(template_file, 'r', encoding='utf-8') as f:\n",
        "        template = json.load(f)\n",
        "    \n",
        "    # Prepare deployment properties\n",
        "    deployment_properties = {\n",
        "        'mode': 'Incremental',\n",
        "        'template': template,\n",
        "        'parameters': parameters_dict\n",
        "    }\n",
        "    \n",
        "    # Start deployment\n",
        "    print('[*] Starting deployment...')\n",
        "    deployment_async = resource_client.deployments.begin_create_or_update(\n",
        "        rg_name,\n",
        "        deployment_name,\n",
        "        {'properties': deployment_properties}\n",
        "    )\n",
        "    \n",
        "    # Poll deployment status\n",
        "    print('[*] Deployment in progress. Polling status...')\n",
        "    start_time = time.time()\n",
        "    last_update = start_time\n",
        "    \n",
        "    while not deployment_async.done():\n",
        "        time.sleep(30)\n",
        "        elapsed = time.time() - start_time\n",
        "        if time.time() - last_update >= 60:\n",
        "            mins = int(elapsed / 60)\n",
        "            secs = int(elapsed % 60)\n",
        "            print(f'[*] Still deploying... {mins}m {secs}s elapsed')\n",
        "            last_update = time.time()\n",
        "    \n",
        "    # Get result\n",
        "    deployment_result = deployment_async.result()\n",
        "    elapsed = time.time() - start_time\n",
        "    mins = int(elapsed / 60)\n",
        "    secs = int(elapsed % 60)\n",
        "    \n",
        "    if deployment_result.properties.provisioning_state == 'Succeeded':\n",
        "        print(f'[OK] Deployment succeeded in {mins}m {secs}s')\n",
        "        return True, deployment_result\n",
        "    else:\n",
        "        print(f'[ERROR] Deployment failed: {deployment_result.properties.provisioning_state}')\n",
        "        if deployment_result.properties.error:\n",
        "            print(f'[ERROR] Error: {deployment_result.properties.error.message}')\n",
        "        return False, deployment_result\n",
        "\n",
        "def get_deployment_outputs(rg_name, deployment_name):\n",
        "    \"\"\"Get deployment outputs\"\"\"\n",
        "    deployment = resource_client.deployments.get(rg_name, deployment_name)\n",
        "    if deployment.properties.outputs:\n",
        "        return {k: v['value'] for k, v in deployment.properties.outputs.items()}\n",
        "    return {}\n",
        "\n",
        "print('[OK] Helper functions defined')\n"
    ]
}

nb['cells'][13] = new_helper_functions

print('[*] Saving notebook...')
with open('master-ai-gateway.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('[OK] Notebook updated with Service Principal authentication!')
print()
print('[OK] Authentication flow:')
print('  1. Try Service Principal from .azure-credentials.env')
print('  2. Fallback to Azure CLI if not found')
print('  3. Provide helpful error messages if both fail')
print()
print('[OK] Next steps:')
print('  1. Run: create_service_principal.ps1')
print('  2. This will create .azure-credentials.env')
print('  3. Run Cell 13 in notebook')
print('  4. Run Cell 15 to deploy')
